import type { Meal, SupermarketPrice } from "./types";
import { portionCostGBP } from "./grocery-prices";

export const DIETARY_RESTRICTIONS = [
  "Vegetarian",
  "Vegan",
  "Gluten-Free",
  "Dairy-Free",
  "Keto",
  "Paleo",
  "Halal",
  "Kosher",
  "Low-Sodium",
  "Nut-Free",
];

export const FITNESS_GOALS = [
  "Weight Loss",
  "Muscle Gain",
  "Maintain Weight",
  "Heart Health",
  "Energy Boost",
  "General Wellness",
];

export const ALLERGIES = [
  "Peanuts",
  "Tree Nuts",
  "Milk",
  "Eggs",
  "Wheat",
  "Soy",
  "Fish",
  "Shellfish",
  "Sesame",
];

const BREAKFAST_MEALS: Meal[] = [
  {
    name: "Greek Yogurt Parfait",
    type: "breakfast",
    calories: 350,
    protein: 20,
    carbs: 45,
    fat: 10,
    prepTime: 5,
    ingredients: [
      { name: "Greek Yogurt", quantity: "1", unit: "cup", estimatedCost: 1.5, category: "Dairy" },
      { name: "Granola", quantity: "0.5", unit: "cup", estimatedCost: 0.8, category: "Cereal" },
      { name: "Mixed Berries", quantity: "0.5", unit: "cup", estimatedCost: 1.2, category: "Produce" },
      { name: "Honey", quantity: "1", unit: "tbsp", estimatedCost: 0.3, category: "Pantry" },
    ],
    instructions: [
      "Layer yogurt in a bowl or glass",
      "Add granola on top",
      "Top with mixed berries",
      "Drizzle with honey",
    ],
    wasteReductionTip: "Buy frozen berries to extend shelf life and reduce waste.",
  },
  {
    name: "Avocado Toast with Eggs",
    type: "breakfast",
    calories: 420,
    protein: 18,
    carbs: 35,
    fat: 24,
    prepTime: 10,
    ingredients: [
      { name: "Whole Wheat Bread", quantity: "2", unit: "slices", estimatedCost: 0.6, category: "Bakery" },
      { name: "Avocado", quantity: "0.5", unit: "whole", estimatedCost: 1.0, category: "Produce" },
      { name: "Eggs", quantity: "2", unit: "large", estimatedCost: 0.6, category: "Dairy" },
      { name: "Salt & Pepper", quantity: "1", unit: "pinch", estimatedCost: 0.05, category: "Pantry" },
    ],
    instructions: [
      "Toast bread until golden",
      "Mash avocado and spread on toast",
      "Fry or poach eggs",
      "Place eggs on toast, season with salt and pepper",
    ],
    wasteReductionTip: "Use overripe avocados for the creamiest spread.",
  },
  {
    name: "Overnight Oats",
    type: "breakfast",
    calories: 380,
    protein: 14,
    carbs: 55,
    fat: 12,
    prepTime: 5,
    ingredients: [
      { name: "Rolled Oats", quantity: "0.5", unit: "cup", estimatedCost: 0.3, category: "Cereal" },
      { name: "Milk", quantity: "0.5", unit: "cup", estimatedCost: 0.4, category: "Dairy" },
      { name: "Chia Seeds", quantity: "1", unit: "tbsp", estimatedCost: 0.4, category: "Pantry" },
      { name: "Banana", quantity: "1", unit: "medium", estimatedCost: 0.25, category: "Produce" },
      { name: "Peanut Butter", quantity: "1", unit: "tbsp", estimatedCost: 0.3, category: "Pantry" },
    ],
    instructions: [
      "Mix oats, milk, and chia seeds in a jar",
      "Refrigerate overnight",
      "Top with sliced banana and peanut butter in the morning",
    ],
    wasteReductionTip: "Use brown-spotted bananas — they're sweeter and would otherwise go to waste.",
  },
  {
    name: "Veggie Egg Scramble",
    type: "breakfast",
    calories: 310,
    protein: 22,
    carbs: 12,
    fat: 20,
    prepTime: 15,
    ingredients: [
      { name: "Eggs", quantity: "3", unit: "large", estimatedCost: 0.9, category: "Dairy" },
      { name: "Bell Pepper", quantity: "0.5", unit: "whole", estimatedCost: 0.5, category: "Produce" },
      { name: "Spinach", quantity: "1", unit: "cup", estimatedCost: 0.6, category: "Produce" },
      { name: "Olive Oil", quantity: "1", unit: "tsp", estimatedCost: 0.15, category: "Pantry" },
    ],
    instructions: [
      "Heat olive oil in a pan",
      "Sauté diced bell pepper for 2 minutes",
      "Add spinach and cook until wilted",
      "Add beaten eggs and scramble until set",
    ],
  },
  {
    name: "Smoothie Bowl",
    type: "breakfast",
    calories: 340,
    protein: 12,
    carbs: 58,
    fat: 8,
    prepTime: 10,
    ingredients: [
      { name: "Frozen Banana", quantity: "1", unit: "whole", estimatedCost: 0.25, category: "Produce" },
      { name: "Frozen Berries", quantity: "0.5", unit: "cup", estimatedCost: 1.0, category: "Produce" },
      { name: "Almond Milk", quantity: "0.5", unit: "cup", estimatedCost: 0.4, category: "Dairy" },
      { name: "Granola", quantity: "0.25", unit: "cup", estimatedCost: 0.4, category: "Cereal" },
    ],
    instructions: [
      "Blend frozen banana, berries, and almond milk until thick",
      "Pour into a bowl",
      "Top with granola and any other toppings",
    ],
    wasteReductionTip: "Freeze overripe bananas for smoothies instead of throwing them away.",
  },
];

const LUNCH_MEALS: Meal[] = [
  {
    name: "Chicken Caesar Salad",
    type: "lunch",
    calories: 480,
    protein: 35,
    carbs: 20,
    fat: 28,
    prepTime: 15,
    ingredients: [
      { name: "Chicken Breast", quantity: "6", unit: "oz", estimatedCost: 2.5, category: "Meat" },
      { name: "Romaine Lettuce", quantity: "2", unit: "cups", estimatedCost: 1.0, category: "Produce" },
      { name: "Parmesan Cheese", quantity: "2", unit: "tbsp", estimatedCost: 0.5, category: "Dairy" },
      { name: "Caesar Dressing", quantity: "2", unit: "tbsp", estimatedCost: 0.4, category: "Pantry" },
      { name: "Croutons", quantity: "0.25", unit: "cup", estimatedCost: 0.3, category: "Bakery" },
    ],
    instructions: [
      "Season and grill chicken breast",
      "Chop romaine lettuce",
      "Slice grilled chicken",
      "Toss lettuce with dressing, top with chicken, parmesan, and croutons",
    ],
    wasteReductionTip: "Use leftover chicken for tomorrow's lunch wrap.",
  },
  {
    name: "Quinoa Buddha Bowl",
    type: "lunch",
    calories: 520,
    protein: 18,
    carbs: 65,
    fat: 22,
    prepTime: 25,
    ingredients: [
      { name: "Quinoa", quantity: "0.5", unit: "cup", estimatedCost: 0.8, category: "Grains" },
      { name: "Chickpeas", quantity: "0.5", unit: "cup", estimatedCost: 0.5, category: "Canned" },
      { name: "Sweet Potato", quantity: "1", unit: "medium", estimatedCost: 0.8, category: "Produce" },
      { name: "Kale", quantity: "1", unit: "cup", estimatedCost: 0.7, category: "Produce" },
      { name: "Tahini", quantity: "2", unit: "tbsp", estimatedCost: 0.5, category: "Pantry" },
    ],
    instructions: [
      "Cook quinoa according to package directions",
      "Roast cubed sweet potato at 400°F for 20 minutes",
      "Drain and rinse chickpeas",
      "Massage kale with a bit of olive oil",
      "Assemble bowl and drizzle with tahini",
    ],
  },
  {
    name: "Turkey & Veggie Wrap",
    type: "lunch",
    calories: 420,
    protein: 28,
    carbs: 40,
    fat: 16,
    prepTime: 10,
    ingredients: [
      { name: "Whole Wheat Tortilla", quantity: "1", unit: "large", estimatedCost: 0.5, category: "Bakery" },
      { name: "Turkey Slices", quantity: "4", unit: "oz", estimatedCost: 2.0, category: "Deli" },
      { name: "Hummus", quantity: "2", unit: "tbsp", estimatedCost: 0.4, category: "Deli" },
      { name: "Mixed Greens", quantity: "1", unit: "cup", estimatedCost: 0.5, category: "Produce" },
      { name: "Tomato", quantity: "0.5", unit: "whole", estimatedCost: 0.4, category: "Produce" },
    ],
    instructions: [
      "Spread hummus on tortilla",
      "Layer turkey slices, greens, and sliced tomato",
      "Roll up tightly and slice in half",
    ],
  },
  {
    name: "Lentil Soup",
    type: "lunch",
    calories: 380,
    protein: 22,
    carbs: 55,
    fat: 6,
    prepTime: 30,
    ingredients: [
      { name: "Red Lentils", quantity: "1", unit: "cup", estimatedCost: 0.8, category: "Grains" },
      { name: "Carrots", quantity: "2", unit: "medium", estimatedCost: 0.4, category: "Produce" },
      { name: "Onion", quantity: "1", unit: "medium", estimatedCost: 0.3, category: "Produce" },
      { name: "Vegetable Broth", quantity: "4", unit: "cups", estimatedCost: 1.0, category: "Canned" },
      { name: "Cumin", quantity: "1", unit: "tsp", estimatedCost: 0.1, category: "Pantry" },
    ],
    instructions: [
      "Sauté diced onion and carrots in olive oil",
      "Add lentils, broth, and cumin",
      "Simmer for 20 minutes until lentils are soft",
      "Season with salt and pepper to taste",
    ],
    wasteReductionTip: "This soup freezes well — make a double batch and freeze portions.",
  },
  {
    name: "Mediterranean Tuna Salad",
    type: "lunch",
    calories: 390,
    protein: 30,
    carbs: 25,
    fat: 20,
    prepTime: 10,
    ingredients: [
      { name: "Canned Tuna", quantity: "1", unit: "can", estimatedCost: 1.5, category: "Canned" },
      { name: "Cucumber", quantity: "0.5", unit: "whole", estimatedCost: 0.4, category: "Produce" },
      { name: "Cherry Tomatoes", quantity: "0.5", unit: "cup", estimatedCost: 0.8, category: "Produce" },
      { name: "Kalamata Olives", quantity: "0.25", unit: "cup", estimatedCost: 0.6, category: "Canned" },
      { name: "Olive Oil", quantity: "1", unit: "tbsp", estimatedCost: 0.2, category: "Pantry" },
      { name: "Lemon Juice", quantity: "1", unit: "tbsp", estimatedCost: 0.15, category: "Produce" },
    ],
    instructions: [
      "Drain tuna and place in bowl",
      "Dice cucumber and halve cherry tomatoes",
      "Combine all ingredients",
      "Dress with olive oil and lemon juice",
    ],
  },
];

const DINNER_MEALS: Meal[] = [
  {
    name: "Grilled Salmon with Vegetables",
    type: "dinner",
    calories: 550,
    protein: 40,
    carbs: 25,
    fat: 30,
    prepTime: 25,
    ingredients: [
      { name: "Salmon Fillet", quantity: "6", unit: "oz", estimatedCost: 4.5, category: "Seafood" },
      { name: "Broccoli", quantity: "1", unit: "cup", estimatedCost: 0.8, category: "Produce" },
      { name: "Brown Rice", quantity: "0.5", unit: "cup", estimatedCost: 0.3, category: "Grains" },
      { name: "Lemon", quantity: "0.5", unit: "whole", estimatedCost: 0.3, category: "Produce" },
      { name: "Olive Oil", quantity: "1", unit: "tbsp", estimatedCost: 0.2, category: "Pantry" },
    ],
    instructions: [
      "Cook brown rice according to package",
      "Season salmon with lemon, salt, and pepper",
      "Grill salmon for 4-5 minutes per side",
      "Steam or roast broccoli",
      "Serve salmon over rice with broccoli",
    ],
  },
  {
    name: "Chicken Stir-Fry",
    type: "dinner",
    calories: 480,
    protein: 35,
    carbs: 45,
    fat: 16,
    prepTime: 20,
    ingredients: [
      { name: "Chicken Breast", quantity: "6", unit: "oz", estimatedCost: 2.5, category: "Meat" },
      { name: "Mixed Stir-Fry Vegetables", quantity: "2", unit: "cups", estimatedCost: 1.5, category: "Produce" },
      { name: "Soy Sauce", quantity: "2", unit: "tbsp", estimatedCost: 0.2, category: "Pantry" },
      { name: "Jasmine Rice", quantity: "0.5", unit: "cup", estimatedCost: 0.3, category: "Grains" },
      { name: "Sesame Oil", quantity: "1", unit: "tsp", estimatedCost: 0.15, category: "Pantry" },
    ],
    instructions: [
      "Cook rice according to package",
      "Slice chicken into thin strips",
      "Stir-fry chicken in sesame oil until cooked through",
      "Add vegetables and soy sauce, cook 3-4 minutes",
      "Serve over rice",
    ],
    wasteReductionTip: "Use up any leftover vegetables from the fridge in this stir-fry.",
  },
  {
    name: "Pasta Primavera",
    type: "dinner",
    calories: 520,
    protein: 16,
    carbs: 72,
    fat: 18,
    prepTime: 25,
    ingredients: [
      { name: "Whole Wheat Pasta", quantity: "2", unit: "oz", estimatedCost: 0.5, category: "Grains" },
      { name: "Zucchini", quantity: "1", unit: "medium", estimatedCost: 0.6, category: "Produce" },
      { name: "Cherry Tomatoes", quantity: "0.5", unit: "cup", estimatedCost: 0.8, category: "Produce" },
      { name: "Garlic", quantity: "2", unit: "cloves", estimatedCost: 0.1, category: "Produce" },
      { name: "Olive Oil", quantity: "2", unit: "tbsp", estimatedCost: 0.3, category: "Pantry" },
      { name: "Parmesan Cheese", quantity: "2", unit: "tbsp", estimatedCost: 0.5, category: "Dairy" },
    ],
    instructions: [
      "Cook pasta according to package, reserve 0.5 cup pasta water",
      "Sauté garlic in olive oil",
      "Add sliced zucchini and halved tomatoes",
      "Toss with pasta and a splash of pasta water",
      "Top with parmesan",
    ],
  },
  {
    name: "Black Bean Tacos",
    type: "dinner",
    calories: 450,
    protein: 18,
    carbs: 58,
    fat: 16,
    prepTime: 15,
    ingredients: [
      { name: "Black Beans", quantity: "1", unit: "can", estimatedCost: 0.8, category: "Canned" },
      { name: "Corn Tortillas", quantity: "3", unit: "small", estimatedCost: 0.4, category: "Bakery" },
      { name: "Avocado", quantity: "0.5", unit: "whole", estimatedCost: 1.0, category: "Produce" },
      { name: "Salsa", quantity: "0.25", unit: "cup", estimatedCost: 0.3, category: "Pantry" },
      { name: "Cilantro", quantity: "2", unit: "tbsp", estimatedCost: 0.2, category: "Produce" },
      { name: "Lime", quantity: "0.5", unit: "whole", estimatedCost: 0.15, category: "Produce" },
    ],
    instructions: [
      "Heat and lightly mash black beans with cumin",
      "Warm tortillas in a dry skillet",
      "Fill tortillas with beans",
      "Top with sliced avocado, salsa, cilantro, and lime juice",
    ],
    wasteReductionTip: "Freeze leftover cilantro in ice cube trays with olive oil.",
  },
  {
    name: "Baked Chicken Thighs with Roasted Vegetables",
    type: "dinner",
    calories: 580,
    protein: 38,
    carbs: 35,
    fat: 32,
    prepTime: 40,
    ingredients: [
      { name: "Chicken Thighs", quantity: "2", unit: "pieces", estimatedCost: 2.0, category: "Meat" },
      { name: "Potatoes", quantity: "2", unit: "medium", estimatedCost: 0.6, category: "Produce" },
      { name: "Carrots", quantity: "2", unit: "medium", estimatedCost: 0.4, category: "Produce" },
      { name: "Onion", quantity: "1", unit: "medium", estimatedCost: 0.3, category: "Produce" },
      { name: "Olive Oil", quantity: "2", unit: "tbsp", estimatedCost: 0.3, category: "Pantry" },
      { name: "Herbs (Thyme, Rosemary)", quantity: "1", unit: "tsp", estimatedCost: 0.2, category: "Pantry" },
    ],
    instructions: [
      "Preheat oven to 425°F",
      "Cut potatoes, carrots, and onion into chunks",
      "Toss vegetables with olive oil and herbs on a baking sheet",
      "Place seasoned chicken thighs on top",
      "Bake for 35-40 minutes until chicken reaches 165°F",
    ],
  },
];

const SNACK_MEALS: Meal[] = [
  {
    name: "Apple with Almond Butter",
    type: "snack",
    calories: 200,
    protein: 5,
    carbs: 28,
    fat: 10,
    prepTime: 2,
    ingredients: [
      { name: "Apple", quantity: "1", unit: "medium", estimatedCost: 0.5, category: "Produce" },
      { name: "Almond Butter", quantity: "1", unit: "tbsp", estimatedCost: 0.5, category: "Pantry" },
    ],
    instructions: ["Slice apple", "Serve with almond butter for dipping"],
  },
  {
    name: "Trail Mix",
    type: "snack",
    calories: 180,
    protein: 6,
    carbs: 18,
    fat: 12,
    prepTime: 1,
    ingredients: [
      { name: "Mixed Nuts", quantity: "0.25", unit: "cup", estimatedCost: 0.8, category: "Pantry" },
      { name: "Dried Fruit", quantity: "2", unit: "tbsp", estimatedCost: 0.4, category: "Pantry" },
    ],
    instructions: ["Combine nuts and dried fruit in a small container"],
    wasteReductionTip: "Make a large batch at the start of the week to save time and money.",
  },
  {
    name: "Hummus & Veggies",
    type: "snack",
    calories: 150,
    protein: 6,
    carbs: 18,
    fat: 7,
    prepTime: 5,
    ingredients: [
      { name: "Hummus", quantity: "0.25", unit: "cup", estimatedCost: 0.5, category: "Deli" },
      { name: "Carrot Sticks", quantity: "1", unit: "cup", estimatedCost: 0.3, category: "Produce" },
      { name: "Celery Sticks", quantity: "0.5", unit: "cup", estimatedCost: 0.2, category: "Produce" },
    ],
    instructions: ["Cut vegetables into sticks", "Serve with hummus for dipping"],
  },
];

// Reprice every ingredient from the per-supermarket UK price table so meal
// costs, shopping lists and store comparisons all use the same real prices.
function repriceMeals(meals: Meal[]): Meal[] {
  return meals.map((meal) => ({
    ...meal,
    ingredients: meal.ingredients.map((ing) => ({
      ...ing,
      estimatedCost: portionCostGBP(ing.name) ?? ing.estimatedCost,
    })),
  }));
}

export const ALL_MEALS = {
  breakfast: repriceMeals(BREAKFAST_MEALS),
  lunch: repriceMeals(LUNCH_MEALS),
  dinner: repriceMeals(DINNER_MEALS),
  snack: repriceMeals(SNACK_MEALS),
};

export const SUPERMARKETS: SupermarketPrice[] = [
  {
    store: "Walmart",
    totalEstimatedCost: 0,
    savings: 0,
    logo: "🏪",
    affiliateUrl: "https://www.walmart.com/grocery",
  },
  {
    store: "Aldi",
    totalEstimatedCost: 0,
    savings: 0,
    logo: "🛒",
    affiliateUrl: "https://www.aldi.us",
  },
  {
    store: "Kroger",
    totalEstimatedCost: 0,
    savings: 0,
    logo: "🏬",
    affiliateUrl: "https://www.kroger.com",
  },
  {
    store: "Costco",
    totalEstimatedCost: 0,
    savings: 0,
    logo: "📦",
    affiliateUrl: "https://www.costco.com",
  },
  {
    store: "Target",
    totalEstimatedCost: 0,
    savings: 0,
    logo: "🎯",
    affiliateUrl: "https://www.target.com/grocery",
  },
];

export const WASTE_REDUCTION_TIPS = [
  "Plan your meals before shopping to buy only what you need.",
  "Store herbs in a glass of water in the fridge to keep them fresh longer.",
  "Freeze leftover bread for toast or breadcrumbs.",
  "Use vegetable scraps to make homemade stock.",
  "Check your fridge before shopping to avoid buying duplicates.",
  "Use the FIFO method: First In, First Out — use older items first.",
  "Freeze overripe bananas for smoothies or banana bread.",
  "Store lettuce with a paper towel to absorb excess moisture.",
  "Repurpose leftovers into new meals (rice → fried rice, chicken → soup).",
  "Learn the difference between 'best by' and 'use by' dates.",
  "Compost food scraps that can't be reused.",
  "Buy frozen vegetables — they last longer and are just as nutritious.",
  "Store potatoes and onions separately to prevent early spoilage.",
  "Batch cook on weekends to reduce weeknight food waste.",
];
